/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface CommerceUser {
  accessToken: string;
  email: string;
  expiresAfter: Generated<string>;
  refreshToken: string;
  updatedAt: Generated<Timestamp>;
  userId: Generated<number>;
}

export interface DB {
  commerceUser: CommerceUser;
}
